### ISSUE TITLE
ctds __init__.py failed if used from executable built with pyinstaller

### ISSUE THREAD

**Issue by umnyaga** [zillow/ctds#98]
I have a python script which works perfectly. I wanted to make an executable out of it using PyInstaller. Once I tried to execute it, I got following error:
$ dist/main
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import ctds
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "ctds/__init__.py", line 8, in <module>
ModuleNotFoundError: No module named 'uuid'
[203506] Failed to execute script 'main' due to unhandled exception!

**Comment by joshuahlang** [comment]
The [`uuid` module](https://docs.python.org/3/library/uuid.html) is part of the python standard library. Are you using some non-standard build of python which wasn't compiled with uuid support by chance?
